database:
  host: localhost # host of your database
  port: 3306 # default port for MariaDB and MySQL
  database: sthin_ice_database # name of your database. A database server can contain multiple databases
  user: root
  password: shadow12